FROM linkeddatafragments/server.js

COPY ./ldfconfig.json /config/config.json
COPY ./diseasome/federationData.hdt /data/diseasome.hdt
COPY ./geocoordinates/federationData.hdt /data/geocoordinates.hdt
COPY ./linkedmdb/federationData.hdt /data/linkedmdb.hdt
